name    'seteam-tomcat'
version '0.1.0'
source 'https://github.com/puppetlabs-seteam/puppet-module-tomcat.git'
author 'Puppet Labs SE Team'
license 'Apache 2.0'
summary 'Puppet Labs SE Team Tomcat Module'
description 'Deploys and manages a Tomcat service'
project_page 'https://github.com/puppetlabs-seteam/puppet-module-tomcat'

dependency 'puppetlabs/java', '>= 0.2.0'
dependency 'nanliu/staging', '>= 0.2.1'
